DROP TABLE IF EXISTS `phm_drug_items`;
CREATE TABLE `phm_drug_items` (
  `drug_id` int(11) NOT NULL,
  `fnm_code` char(10) NOT NULL,
  `pharmaceutical_form_id` int(11) NOT NULL,
  `therapeutic_group_id` int(11) NOT NULL,
  `therapeutic_class_id` int(11) NOT NULL,
  `uuid` char(38) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT '0',
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `retired` tinyint(1) NOT NULL DEFAULT '0',
  `retired_by` int(11) DEFAULT NULL,
  `date_retired` datetime DEFAULT NULL,
  `retire_reason` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`drug_id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `fnm_code` (`fnm_code`),
  KEY `phm_drug_items_pharmaceutical_form_fk` (`pharmaceutical_form_id`),
  KEY `phm_drug_items_therapeutic_group_fk` (`therapeutic_group_id`),
  KEY `phm_drug_items_therapeutic_class_fk` (`therapeutic_class_id`),
  KEY `phm_drug_items_creator_fk` (`creator`),
  KEY `phm_drug_items_changed_by_fk` (`changed_by`),
  KEY `phm_drug_items_retired_by_fk` (`retired_by`),
  CONSTRAINT `phm_drug_items_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `phm_drug_items_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `phm_drug_items_drug_fk` FOREIGN KEY (`drug_id`) REFERENCES `drug` (`drug_id`),
  CONSTRAINT `phm_drug_items_pharmaceutical_form_fk` FOREIGN KEY (`pharmaceutical_form_id`) REFERENCES `concept` (`concept_id`),
  CONSTRAINT `phm_drug_items_retired_by_fk` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `phm_drug_items_therapeutic_class_fk` FOREIGN KEY (`therapeutic_class_id`) REFERENCES `concept` (`concept_id`),
  CONSTRAINT `phm_drug_items_therapeutic_group_fk` FOREIGN KEY (`therapeutic_group_id`) REFERENCES `concept` (`concept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;