SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO serialized_object(`name`, `description`, `type`, `subtype`, `serialization_class`, `serialized_data`, `date_created`, `creator`, `date_changed`, `changed_by`, `retired`, `date_retired`, `retired_by`, `retire_reason`, `uuid`)
VALUES ('SQL PARA PRODUÇÃO DE DADOS DE CD4: SOLICITACÃO CDC - MISAU', 'Data set para produção de dados de cd4 requisição de CDC e MISAU', 'org.openmrs.module.reporting.dataset.definition.DataSetDefinition', 'org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition', 'org.openmrs.module.reporting.serializer.ReportingSerializer', '<org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition id=\"1\" uuid=\"ab960ae6-fe08-43d9-904d-2accc64126d8\" retired=\"false\">\n  <name>SQL PARA PRODUÇÃO DE DADOS DE CD4: SOLICITACÃO CDC - MISAU</name>\n  <description>Data set para produção de dados de cd4 requisição de CDC e MISAU</description>\n  <creator id=\"2\" uuid=\"85a09a66-1e3d-11e0-acca-000c29d83bf2\"/>\n  <dateCreated id=\"3\">2017-02-02 09:35:59 CAT</dateCreated>\n  <dateChanged id=\"4\">2017-02-02 09:36:23 CAT</dateChanged>\n  <parameters id=\"5\"/>\n  <sqlQuery>select * from cd4_dados</sqlQuery>\n</org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition>', '2017-02-02 09:35:59', @user_id, '2017-02-02 09:36:23', null, '0', null, null, null, 'ab960ae6-fe08-43d9-904d-2accc64126d8');

INSERT INTO serialized_object(`name`, `description`, `type`, `subtype`, `serialization_class`, `serialized_data`, `date_created`, `creator`, `date_changed`, `changed_by`, `retired`, `date_retired`, `retired_by`, `retire_reason`, `uuid`)
VALUES ('CD4 DATA - REQUEST FROM CDC-MOH', 'CD4 DATA - REQUEST FROM CDC-MOH', 'org.openmrs.module.reporting.report.definition.ReportDefinition', 'org.openmrs.module.reporting.report.definition.ReportDefinition', 'org.openmrs.module.reporting.serializer.ReportingSerializer', '<org.openmrs.module.reporting.report.definition.ReportDefinition id=\"1\" uuid=\"21615ac8-73a0-4707-971c-da5e6f64b767\" retired=\"false\">\n  <name>CD4 DATA - REQUEST FROM CDC-MOH</name>\n  <description>CD4 DATA - REQUEST FROM CDC-MOH</description>\n  <creator id=\"2\" uuid=\"85a09a66-1e3d-11e0-acca-000c29d83bf2\"/>\n  <dateCreated id=\"3\">2017-02-02 09:37:36 CAT</dateCreated>\n  <dateChanged id=\"4\">2017-02-02 09:38:50 CAT</dateChanged>\n  <parameters id=\"5\"/>\n  <dataSetDefinitions class=\"linked-hash-map\" id=\"6\">\n    <entry>\n      <string>CD4CDCMISAU</string>\n      <org.openmrs.module.reporting.evaluation.parameter.Mapped id=\"7\">\n        <parameterizable class=\"org.openmrs.module.reporting.dataset.definition.SqlDataSetDefinition\" id=\"8\" uuid=\"ab960ae6-fe08-43d9-904d-2accc64126d8\"/>\n        <parameterMappings id=\"9\"/>\n      </org.openmrs.module.reporting.evaluation.parameter.Mapped>\n    </entry>\n  </dataSetDefinitions>\n</org.openmrs.module.reporting.report.definition.ReportDefinition>', '2017-02-02 09:37:36', @user_id, '2017-02-02 09:38:50', null, '0', null, null, null, '21615ac8-73a0-4707-971c-da5e6f64b767');

INSERT INTO reporting_report_design(`uuid`, `name`, `description`, `renderer_type`, `properties`, `creator`, `date_created`, `changed_by`, `date_changed`, `retired`, `retired_by`, `date_retired`, `retire_reason`, `report_definition_uuid`)
VALUES ('696cd0d2-9e77-4838-bc5c-a7aafaa40307', 'CD4 DATA - REQUEST FROM CDC-MOH', 'CD4 DATA - REQUEST FROM CDC-MOH', 'org.openmrs.module.reporting.report.renderer.XlsReportRenderer', '#Thu Feb 02 16:18:33 CAT 2017\r\n', @user_id, '2017-02-02 09:41:06', null, null, '0', null, null, null, '21615ac8-73a0-4707-971c-da5e6f64b767');

SET FOREIGN_KEY_CHECKS=1;